services:
  python_app:
    command: tail -F /dev/null
    depends_on:
      - database
    build:
        context: ./
        dockerfile: Dockerfile
    environment:
        AWS_KEY: ""
        AWS_SECRET: ""
        S3_BUCKET: ""
  database:
    image: docker.io/library/postgres:14
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "test"
        POSTGRES_DB: "postgres"
    ports:
      - 15432:5432
    volumes:
      - localvolume:/var/lib/postgresql/data
volumes:
  localvolume: null
